# Generated by Django 6.0 on 2026-01-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuariohtp_groups_usuariohtp_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariohtp',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
