# Generated by Django 6.0 on 2026-02-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_hora_fin_reserva_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='resultado',
            field=models.CharField(blank=True, choices=[('usada', 'Usada'), ('no_show', 'No se presentó'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_uso', 'En uso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
