# Generated by Django 6.0 on 2026-02-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_estado'),
        ('reserva', '0003_remove_reserva_hora_reserva_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden'),
        ),
    ]
