# Generated by Django 6.0 on 2026-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_reserva_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_deposito',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
