# Generated by Django 6.0 on 2026-04-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reserva_monto_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
