# Generated by Django 6.0 on 2026-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
