# Generated by Django 6.0 on 2026-01-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ordenes', '0002_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='ordenes.orden'),
        ),
    ]
