# Generated by Django 6.0 on 2026-01-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado', 'Entregado'), ('canelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
