# Generated by Django 6.0 on 2026-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
