# Generated by Django 6.0 on 2026-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en preparacion', 'En preparación'), ('entregado', 'Entregado'), ('canelado', 'Cancelado')], default='En preparación', max_length=20),
        ),
    ]
